### ISSUE TITLE
Issue dailymotion contents with Youtube-DL >= 2019.11.28

### ISSUE THREAD

**Issue by wwark** [willforde/script.module.codequick#36]
Hi Wilforde,

How are you?
Since this release (https://github.com/ytdl-org/youtube-dl/releases/tag/2019.11.28), we have issue to play dailymotion content.
At this release, we have some updates related to dailymotion.

I updated the core youtube-dl on the ruuk plugin using this procedure https://catch-up-tv-and-more.github.io/faq/

I have this issue and the issue is raised in the resolver of codequick.
'2020-03-21 15:09:37.051 T:140493386028800   ERROR: [debug] Encodings: locale UTF-8, fs UTF-8, out missing (instance), pref UTF-8
2020-03-21 15:09:37.051 T:140493386028800   DEBUG: .
2020-03-21 15:09:37.051 T:140493386028800   ERROR: [debug] youtube-dl version 2019.11.28
2020-03-21 15:09:37.051 T:140493386028800   DEBUG: .
2020-03-21 15:09:37.067 T:140493386028800   ERROR: [debug] Python version 2.7.17 (CPython) - Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic
2020-03-21 15:09:37.067 T:140493386028800   DEBUG: .
2020-03-21 15:09:37.384 T:140493386028800   ERROR: [debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
2020-03-21 15:09:37.384 T:140493386028800   DEBUG: .
2020-03-21 15:09:37.384 T:140493386028800   ERROR: [debug] Proxy map: {}
2020-03-21 15:09:37.384 T:140493386028800   DEBUG: .
2020-03-21 15:09:37.393 T:140493386028800  NOTICE: script.module.youtube.dl: ERROR: _getYoutubeDLVideo() failed
2020-03-21 15:09:37.396 T:140493386028800  NOTICE: Traceback (most recent call last):
                                              File "/home/wark/.kodi/addons/script.module.youtube.dl/lib/YDStreamExtractor.py", line 383, in getVideoInfo
                                                info = _getYoutubeDLVideo(url, quality, resolve_redirects)
                                              File "/home/wark/.kodi/addons/script.module.youtube.dl/lib/YDStreamExtractor.py", line 181, in _getYoutubeDLVideo
                                                r = ytdl.extract_info(url, download=False)
                                              File "/home/wark/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/YoutubeDL.py", line 797, in extract_info
                                                ie_result = ie.extract(url)
                                              File "/home/wark/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/extractor/common.py", line 530, in extract
                                                ie_result = self._real_extract(url)
                                              File "/home/wark/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/extractor/dailymotion.py", line 235, in _real_extract
                                                'password: "%s"' % self._downloader.params.get('videopassword') if password else None)
                                              File "/home/wark/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/extractor/dailymotion.py", line 50, in _call_api
                                                cookies = self._get_dailymotion_cookies()
                                              File "/home/wark/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/extractor/dailymotion.py", line 31, in _get_dailymotion_cookies
                                                return self._get_cookies('https://www.dailymotion.com/')
                                              File "/home/wark/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/extractor/common.py", line 2831, in _get_cookies
                                                return compat_cookies.SimpleCookie(req.get_header('Cookie'))
                                              File "/usr/lib/python2.7/Cookie.py", line 583, in __init__
                                                if input: self.load(input)
                                              File "/usr/lib/python2.7/Cookie.py", line 643, in load
                                                for k, v in rawdata.items():
                                            AttributeError: 'unicode' object has no attribute 'items'
2020-03-21 15:09:37.397 T:140493386028800   FATAL: [Catch-up-TV-&-More.support] Unable to resolve url
                                            Traceback (most recent call last):
                                              File "/home/wark/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 295, in run_callback
                                                redirect = parent_ins._process_results(results)
                                              File "/home/wark/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 375, in _process_results
                                                raise RuntimeError(self.localize(NO_VIDEO))
                                            RuntimeError: Unable to resolve url
2020-03-21 15:09:37.397 T:140493386028800 WARNING: ###### debug ######

Thanks for your help

@SylvainCecchetto

**Comment by wwark** [comment]
hi,
after checking more deeply it is not a codequick issue.
I close this ticket.

Thanks,
