### ISSUE TITLE
No module named htmlement

### ISSUE THREAD

**Issue by sy6sy2** [willforde/script.module.codequick#6]
Hi!

On your examples you use HTMLement in order to parse the web page.
I try to do the same thing as in your tutorial but it seems that Kodi doesn't find the module :-/

```
FATAL: [Catch-up-TV-&-More-—-Test-CodeQuick.support] No module named htmlement
                                            Traceback (most recent call last):
                                              File "/Users/sylvain/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/support.py", line 312, in dispatch
                                                controller_ins._execute_route(route.callback)
                                              File "/Users/sylvain/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/route.py", line 92, in _execute_route
                                                success = self.__add_listitems(listitems)
                                              File "/Users/sylvain/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/route.py", line 97, in __add_listitems
                                                raw_listitems = validate_listitems(raw_listitems)
                                              File "/Users/sylvain/Library/Application Support/Kodi/addons/script.module.codequick/lib/codequick/route.py", line 38, in validate_listitems
                                                raw_listitems = list(raw_listitems)
                                              File "/Users/sylvain/Library/Application Support/Kodi/addons/plugin.video.catchuptvandmorecodequick/resources/lib/channels/fr/tf1.py", line 144, in list_shows
                                                u"ul", attrs={'class': 'filters_2 contentopen'})
                                              File "/Users/sylvain/Library/Application Support/Kodi/addons/script.module.codequick/lib/urlquick.py", line 1313, in parse
                                                from htmlement import HTMLement
                                            ImportError: No module named htmlement
```

**Comment by willforde** [comment]
It is in the kodi (krypton) official repository. All my addon's use it. Kodi must not have installed it for you.
http://mirrors.kodi.tv/addons/krypton/script.module.htmlement/script.module.htmlement-0.2.3.zip

**Comment by willforde** [comment]
Unfortunately the site that the documentation uses "http://metalvideo.com/", is down at moment and has been for a little while now. Sorry about that. You can have a look at my other addon's if that any help.

**Comment by sy6sy2** [comment]
Sorry it's my fault, I had already copy the script.module.htmlement folder in Kodi Addons folder but I forget that Kodi don't enable the new add-on by default.
After enabling it in the dependency section of Kodi I don't have this Import error ;-)
